//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A4DEDC_CTReportEntities : DbContext
    {
        public DB_A4DEDC_CTReportEntities()
            : base("name=DB_A4DEDC_CTReportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consolidate> Consolidate { get; set; }
        public virtual DbSet<HistoryRealTime> HistoryRealTime { get; set; }
        public virtual DbSet<Partner> Partner { get; set; }
        public virtual DbSet<RegistryRealTime> RegistryRealTime { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<Sector> Sector { get; set; }
        public virtual DbSet<Vehicle> Vehicle { get; set; }
        public virtual DbSet<HistoryCollection> HistoryCollection { get; set; }
        public virtual DbSet<PartnerVehicleDetails> PartnerVehicleDetails { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
