//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CtReportsEntities : DbContext
    {
        public CtReportsEntities()
            : base("name=CtReportsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HistoryCollection> HistoryCollection { get; set; }
        public virtual DbSet<HistoryRealTime> HistoryRealTime { get; set; }
        public virtual DbSet<Partner> Partner { get; set; }
        public virtual DbSet<RegistryRealTime> RegistryRealTime { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<Sector> Sector { get; set; }
        public virtual DbSet<Vehicle> Vehicle { get; set; }
        public virtual DbSet<Consolidate> Consolidate { get; set; }
    
        public virtual ObjectResult<SPConsolidated_Result> SPConsolidated(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPConsolidated_Result>("SPConsolidated", idParameter);
        }      
    
        public virtual ObjectResult<SPDetailedByVehicle_Result> SPDetailedByVehicle(string numberId, string dateStart, string dateFinal)
        {
            var numberIdParameter = numberId != null ?
                new ObjectParameter("numberId", numberId) :
                new ObjectParameter("numberId", typeof(string));
    
            var dateStartParameter = dateStart != null ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(string));
    
            var dateFinalParameter = dateFinal != null ?
                new ObjectParameter("dateFinal", dateFinal) :
                new ObjectParameter("dateFinal", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPDetailedByVehicle_Result>("SPDetailedByVehicle", numberIdParameter, dateStartParameter, dateFinalParameter);
        }                     
    
        public virtual ObjectResult<SPconsolidatedDateOfVehicle_Result> SPconsolidatedDateOfVehicle(string startDay, string startMonth, string startYear, string finalDay, string finalMonth, string finalYear, string id)
        {
            var startDayParameter = startDay != null ?
                new ObjectParameter("startDay", startDay) :
                new ObjectParameter("startDay", typeof(string));
    
            var startMonthParameter = startMonth != null ?
                new ObjectParameter("startMonth", startMonth) :
                new ObjectParameter("startMonth", typeof(string));
    
            var startYearParameter = startYear != null ?
                new ObjectParameter("startYear", startYear) :
                new ObjectParameter("startYear", typeof(string));
    
            var finalDayParameter = finalDay != null ?
                new ObjectParameter("finalDay", finalDay) :
                new ObjectParameter("finalDay", typeof(string));
    
            var finalMonthParameter = finalMonth != null ?
                new ObjectParameter("finalMonth", finalMonth) :
                new ObjectParameter("finalMonth", typeof(string));
    
            var finalYearParameter = finalYear != null ?
                new ObjectParameter("finalYear", finalYear) :
                new ObjectParameter("finalYear", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPconsolidatedDateOfVehicle_Result>("SPconsolidatedDateOfVehicle", startDayParameter, startMonthParameter, startYearParameter, finalDayParameter, finalMonthParameter, finalYearParameter, idParameter);
        }
    }
}
