//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryCollection
    {
        public string IdHistoryCollection { get; set; }
        public string IdVehicle { get; set; }
        public string IdRoute { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateFinal { get; set; }
        public Nullable<long> MinutesV { get; set; }
        public Nullable<long> Passenger { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Kilometers { get; set; }
        public Nullable<double> Laps { get; set; }
        public string IdSector { get; set; }
        public Nullable<double> LapsManual { get; set; }
        public string IdRegistry { get; set; }
        public Nullable<double> InRegistryRealTime { get; set; }
        public Nullable<double> InSector { get; set; }
        public Nullable<double> InRoute { get; set; }
        public Nullable<double> AmountDiscountedBrands { get; set; }
        public Nullable<long> Blocks { get; set; }
        public Nullable<long> UpsDoorOne { get; set; }
        public Nullable<long> DownsDoorOne { get; set; }
        public Nullable<long> BlocksDoorOne { get; set; }
        public Nullable<long> UpsDoorTwo { get; set; }
        public Nullable<long> DownsDoorTwo { get; set; }
        public Nullable<long> BlocksDoorTwo { get; set; }
        public Nullable<double> InVehicle { get; set; }
        public Nullable<double> InHistoryRealTime { get; set; }
        public string IdConsolidate { get; set; }
    
        public virtual Consolidate Consolidate { get; set; }
        public virtual Route Route { get; set; }
        public virtual Sector Sector { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
