//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerVehicleDetails
    {
        public int InPartner { get; set; }
        public string IdVehicle { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
