//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistryRealTime
    {
        public string IdRegistryRealTime { get; set; }
        public string IdVehicle { get; set; }
        public string IdSector { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Length { get; set; }
        public string Latitute { get; set; }
        public Nullable<long> Speed { get; set; }
        public Nullable<long> OnboardPassengers { get; set; }
        public Nullable<long> Uploads { get; set; }
        public Nullable<long> Dows { get; set; }
        public Nullable<double> InRegistryRealTime { get; set; }
    }
}
